### ISSUE TITLE
How to get spark-benchmarks-dfsio-0.1.0-with-dependencies.jar??

### ISSUE THREAD

**Issue by Mohesam** [BBVA/spark-benchmarks#2]
Hello; 
I am interested to run this benchmark, but I can't get spark-benchmarks-dfsio-0.1.0-with-dependencies.jar can you please share it?

Thanks

**Comment by aalda** [comment]
Hi,

Have you tried to build the project? First you need to install sbt and then just type ```sbt clean assembly```. The jar should be located in the following path:

```./spark-benchmarks/dfsio/target/scala-2.11/```

**Comment by Mohesam** [comment]
Thanks for your answer, I consider myself new to this domain. I have downloaded sbt-1.2.6.tgz and extracted it. Then I have run the command "sbt clean assembly" but it gave me an error of command not found. Anything is missing?

**Comment by aalda** [comment]
You need to add the sbt command to the ```PATH``` in order to be able to execute anywhere:

```
export SBT_HOME=/path/to/sbt
export PATH=$PATH:$SBT_HOME/bin
```

You should add these lines to your ```~/.bashrc``` file to avoid repeating them on every terminal.

**Comment by Mohesam** [comment]
Thanks for your supprt.. Now sbt works. I have run "sbt clean assembly", but it looks missing a file or a folder to run on.
I have downloaded the code spark-benchmarks-master.zip and unzipped it. So, Do you mean that I should run "sbt clean assembly sbt spark-benchmarks-master"?

**Comment by Mohesam** [comment]
It is just working now, I have run "sbt clean assembly" inside the spark-benchmarks-master folder.. Thanks again

**Comment by aalda** [comment]
I'm glad to hear that
