### ISSUE TITLE
Error: Can't load main class from JAR file

### ISSUE THREAD

**Issue by Mohesam** [BBVA/spark-benchmarks#3]
Hello Alvaro;

I used the same command, for writing, but got an error or cannot load main class from JAR file. The error screenshot is attached.
[Doc2.pdf](https://github.com/BBVA/spark-benchmarks/files/2512751/Doc2.pdf)

**Comment by aalda** [comment]
It seems not to be able to parse the submit arguments correctly. Maybe you should to include the spark protocol in your master URL (on the assumption  you are using the standalone cluster): 

```--master spark://spark01:4040```

**Comment by Mohesam** [comment]
Yes, it is a standalone cluster. I have changed it to --master spark://spark01:7077 but got the same error. If you have time, I can send you a Skype session to check it together.

**Comment by aalda** [comment]
Try removing all backslashes if you are executing the command on a single line. You also have a typo in the ```--executor-core``` argument, it should be ```--executor-cores```.

**Comment by Mohesam** [comment]
I have done editings, now it looks see the JAR file, but shows the attached Java error "unable to load native-hadoop library for your platform using builtin-Java classes"
[JAVAError.pdf](https://github.com/BBVA/spark-benchmarks/files/2515832/JAVAError.pdf)

**Comment by aalda** [comment]
That's just a warning. It's telling you that Spark can't find C++ Hadoop libraries, but it's using Java ones as a fallback. Don't worry about that. 

The real problem comes again with parsing. If you look closely you'll see you're typing the command, with all parameters, twice consecutively.
